Update example repo after renaming dataplane -> forwarder
networkservicemesh/examples pull request #54
Opened 2019-10-20 15:32 UTC by denis-tingajkin

Signed-off-by: denis-tingajkin <denis.tingajkin@xored.com>``

2019-10-20 16:10 UTC, nickolaev reviewed
It looks like the strings in the go code are jist wrong. We should just replace them with relevant ones.

2019-10-20 18:54 UTC, denis-tingajkin commented
@nickolaev can you provide an example of wrong strings in the go code?

2019-10-20 19:31 UTC, nickolaev requested changes
Added suggested string substitutions.

2019-10-20 19:31 UTC, nickolaev commented on examples/proxy/proxy-nsc/cmd/nsc.go
> +	closer := jaeger.InitJaeger("vppagent-forwarder")
"vppagent-forwarder" --> "proxy-nsc"

2019-10-20 19:31 UTC, nickolaev commented on examples/proxy/proxy-nsc/cmd/nsc.go
> +	span := spanhelper.FromContext(context.Background(), "Start.VPPAgent.Forwarder")
"Start.VPPAgent.Forwarder" --> "Start.Proxy.NSC"

2019-10-20 19:31 UTC, nickolaev commented on examples/vpp-icmp/vppagent-client/cmd/client.go
> +	closer := jaeger.InitJaeger("vppagent-forwarder")
"vppagent-forwarder" --> "vppagent-client"

2019-10-20 19:31 UTC, nickolaev commented on examples/vpp-icmp/vppagent-client/cmd/client.go
> +	span := spanhelper.FromContext(context.Background(), "Start.VPPAgent.Forwarder")
"Start.VPPAgent.Forwarder" --> "Start.VPPAgent.Client"

2019-10-21 03:57 UTC, denis-tingajkin commented
@nickolaev got it. Thanks, fixed

2019-10-21 04:27 UTC, nickolaev approved these changes

2019-10-21 20:02 UTC, merged